### ISSUE TITLE
help to implement in a simple flutter project

### ISSUE THREAD

**Issue by gurugeek** [alexelisenko/audio_player_service#1]
hello @alexelisenko first of all thanks for working on this as I struggled to get audio player to work on my small app and play audio on the background. The problem was that on lock screen there is no media controller..but your example works fine so I was wondering if you would be interested (Paid work) to implement your package on my simple app. I think that since you wrote the package it would be much easier for you and of course I will be happy to pay for your time.
Thanks for letting me know!

**Comment by alexelisenko** [comment]
@gurugeek I do not have time to take anything new on unfortunately, but, feel free to ask questions on how to use/implement this in your project, i'll do my best to answer promptly.
